services:
  ddns:
    image: jellyqwq/ddns-tencent:latest
    container_name: ddns-tencent
    restart: unless-stopped
    network_mode: host
    environment:
      - Ipv4Domain=example.com
      - Ipv4SubDomain=ipv4.ddns
      - Ipv4RecordLine=默认
      - Ipv4RecordId=xxxxxxxx
      - Ipv6Domain=example.com
      - Ipv6SubDomain=ipv6
      - Ipv6RecordLine=默认
      - Ipv6RecordId=xxxxxxxx
      - SecretId=xxxxxxxxxxxxxxxxxxx
      - SecretKey=xxxxxxxxxxxxxxxxxxx
      - CronExpression=*/5 * * * *